- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    #list of string
    #map is key-value pair
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'mailx', state: 'installed'}

  