#number
#string 
#map
#boolean

- name: ansible varibale data types
  hosts: localhosts
  vars:
  - AGE: 30 #number
  - NAME: "Sumati" #string
  - isDevOps: true #boolean
  - Skills:
    - DevOps
    - AWS
    - Docker
  - EXPERIENCE: #map
      DevOps: 7
      AWS: 5
      Docker: 4
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "{{AGE}}"
  - name: print string variable
    ansible.builtin.debug:
      msg: "{{NAME}}"
  - name: print boolean variable
    ansible.builtin.debug:
      msg: "{{isDevOps}}"
  - name: print list variable
    ansible.builtin.debug:
      msg: "{{Skills}}"
  - name: print map variable
    ansible.builtin.debug:
      msg: "{{EXPERIENCE}}"