- name: variables in task level
  hosts: localhost
  #this variables are play or parent level
  vars:
  - money: "10000 RS"
    land: "100 hectoars"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and overrides
  vars: 
  -  money: "20000 RS"
     houses: "3 houses"   
     ansible.builtin.debug:
        msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"